name: flutter_local_storage_practice
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1



environment:
  sdk: '>=2.19.2 <3.0.0'
  
  
  

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hive: ^2.2.3
  path_provider: ^2.0.12
  hive_flutter: ^1.1.0


dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700